GaloisInc/cclyzerpp

.dockerignore
.github/workflows/ci.yml
Dockerfile
PointerAnalysis.cpp
contrib/README.md
contrib/nix/shell.nix
doc/build.rst
doc/docker.rst
scripts/gha-docker-build

CI and Docker

---

.github/workflows/ci.yml
docker/dev.dockerfile

ci, docker: Parallelize tests with pytest-xdist

---

.github/workflows/ci.yml
doc/docker.rst
scripts/gha-docker-build

ci: Only push Docker images to GHCR on releases

---

FactGenerator/include/predicates.inc
FactGenerator/src/InstructionVisitor.cpp

FactGenerator: Consistent names for multi-word opcodes

---

.github/workflows/ci.yml
docker/dev.dockerfile
scripts/lint.sh
test/mypy.ini
test/pa_invariant_test.py

ci: Lint with Mypy

---

.github/workflows/ci.yml

ci: Fix release job by logging into GHCR

---

scripts/run.py

Previously had a bug where it wasn't properly comparing outputs.

Improve script for human-readable diffs of analysis outputs

---

.github/workflows/ci.yml
doc/dev.rst
pkg/.fpm
pkg/pkg.sh

Next steps:
- Integrate packaging into CMake
- Install package in Docker dist image
- Attach package to releases

Package for Debian with fpm

---

.github/workflows/ci.yml
scripts/gha-docker-build
scripts/version.sh

ci: Attach Debian package to releases

---

datalog/debug.project
datalog/points-to/cplusplus-exceptions.dl
datalog/points-to/cplusplus.dl
datalog/points-to/debug.dl
datalog/points-to/subset.dl
datalog/points-to/unification.dl

datalog: Don't instantiate `ThrowInstruction` component

---

doc/build.rst

doc: Mention Debian packages

---

.github/workflows/ci.yml
doc/build.rst
doc/dev.rst
doc/overview.rst
scripts/gha-docker-build

doc, ci: New release process

---

doc/.gitignore
doc/Makefile
doc/conf.py
doc/requirements.txt
doc/templates/layout.html

doc: Change Sphinx theme, add "fork me on Github" banner

---

.github/workflows/ci.yml

ci: Fix output path of documentation build

---

.github/workflows/ci.yml
FactGenerator/src/TypeVisitor.cpp
docker/dev.dockerfile
docker/dist.dockerfile
src/PointerAnalysis.cpp
src/PointerAnalysis.h

ci, docker: Compile against LLVM nightly (LLVM 16)

---

.clang-tidy
FactGenerator/include/FactGenerator.hpp
FactGenerator/src/Constants.cpp
FactGenerator/src/ContextManager.hpp
FactGenerator/src/FactGenerator.cpp
FactGenerator/src/FactWriter.cpp
FactGenerator/src/Functions.cpp
FactGenerator/src/Globals.cpp
FactGenerator/src/InstructionVisitor.cpp
FactGenerator/src/LlvmEnums.cpp
FactGenerator/src/Main.cpp
FactGenerator/src/Options.cpp
FactGenerator/src/RefmodeEngine.cpp
FactGenerator/src/RefmodeEngineImpl.cpp
FactGenerator/src/RefmodeEngineImpl.hpp
FactGenerator/src/TypeVisitor.cpp

... and apply the relevant auto-fixes.

FactGenerator: Enable more clang-tidy checks

---

FactGenerator/include/MalformedModule.hpp
FactGenerator/include/Unknown.hpp
FactGenerator/src/Functions.cpp
FactGenerator/src/Globals.cpp
FactGenerator/src/InstructionVisitor.cpp
FactGenerator/src/LlvmEnums.cpp
FactGenerator/src/Main.cpp
FactGenerator/src/TypeVisitor.cpp
datalog/schema/atomicrmw-instr.dl

Fixes #129. Fixes #123. Fixes #131.

FactGenerator: Cleanup

---

CMakeLists.txt
FactGenerator/include/InstructionVisitor.hpp
FactGenerator/src/ContextManager.hpp
FactGenerator/src/FactGenerator.cpp
FactGenerator/src/InstructionVisitor.cpp
FactGenerator/src/RefmodeEngine.cpp
FactGenerator/src/TypeVisitor.cpp
src/PAInterface.cpp
src/PAInterface.h
src/PointerAnalysis.cpp

FactGenerator: `-Werror`

---

datalog/points-to/class-type.dl

See here https://github.com/souffle-lang/souffle/issues/2079#issuecomment-924605121

Fix building with recent versions of souffle

---

doc/unsoundness.rst

docs: discuss removal of unsupported instructions

---

docker/dev.dockerfile

dev.dockerfile: Pin Souffle 2.3

---

FactGenerator/include/InstructionVisitor.hpp
FactGenerator/include/predicates.inc
FactGenerator/src/InstructionVisitor.cpp
datalog/CMakeLists.txt
datalog/export/debug-output-extended.dl
datalog/export/debug-output.dl
datalog/schema/fneg-instr.dl
datalog/schema/freeze-instr.dl
datalog/schema/instr.dl
datalog/schema/schema.project

Hey @langston-barrett! I've added rudimentary support for the `fneg` and `freeze` instructions. Let me know what you think!

fact-gen: support fneg and freeze instructions
